[package]
name = "task-manager"
version = "0.1.0"
edition = "2018"

[dependencies]
task-manager-types = { path = "types" }
libc = "0.2.92"
actix-web = "3.3.2"
serde = { version = "1.0.125", features = ["derive"] }
actix-files = "0.5.0"

[workspace]
members = ["types", "client"]
